### ISSUE TITLE
Suggestions: Custom template path, block to many invalid logins

### ISSUE THREAD

**Issue by EternalBlack** [verbb/knock-knock#1]
I would like to suggest some features :).

1. It would be nice if there would be an option to provide a custom twig template. This probably would require to make the login form accessible via Twig so it can be integrated easily. (This maybe would also open up the possibility to have this kind of password protection for sections, like a `single`)
2. Block to many invalid login attempts so `brute force` wont be an option anymore. I would suggest to have an option in the control panel. Should be server based, like saving and blocking the IP for 24h or so.

**Comment by engram-design** [comment]
Love it! Will add it to our list.

**Comment by ljclark** [comment]
Are there any plans/updates on the above FR's, particularly Number 1 where we can load our own template in to have control over styling? :)

**Comment by fbnntt** [comment]
I'm also interested in both FR's.

**Comment by engram-design** [comment]
Added in [1.1.0](https://github.com/verbb/knock-knock/releases/tag/1.1.0)

**Comment by EternalBlack** [comment]
Nice work, already loving it!

But also just wondering: How does one achieve hiding the password-input-field if there already where `Too many invalid attempts`? I'd like to reduce load on the server at any cost🙈.

**Comment by engram-design** [comment]
@EternalBlack You'll need to do a custom template, but could check:
```
{% if errors is defined and errors.password == 'Too many invalid attempts' %}
    // Don't show input
```
