### ISSUE TITLE
Craft 3.4 breaks CSS layout

### ISSUE THREAD

**Issue by timmyomahony** [verbb/knock-knock#16]
### Description

Craft 3.4 updates the layout of the control panel, meaning the styling of Knock Knock is now off

<img width="1279" alt="Screenshot 2020-01-29 at 14 29 17" src="https://user-images.githubusercontent.com/615149/73365174-be6ae380-42a3-11ea-91ad-fcab3091ed39.png">

### Steps to reproduce

1. Update to Craft 3.4
2. View lock-screen

### Additional info

- Plugin version: 1.1.2
- Craft version: 3.4

**Comment by engram-design** [comment]
Fixed in [1.2.0](https://github.com/verbb/knock-knock/releases/tag/1.2.0)
