### ISSUE TITLE
Add support for wildcard password-protection

### ISSUE THREAD

**Issue by nettum** [verbb/knock-knock#17]
### Description
It would be nice to password-protect all entries inside a channel or structure without knowing what urls will exactly live there as they are generated dynamic by the entry slug.

This _could_ be done by allowing wildcard-routes to the "Protected URLs" and modify the check for protected urls.

I guess it could be implemented with preg_match and regex or something like this which only checks for `*` at the end of the URLs added to "Protected URLs":
```
if ($settings->getProtectedUrls()) {
    $matchProtectedUrl = false;
    foreach ($settings->getProtectedUrls() as $protectedUrl) {
        if (substr($protectedUrl, -1) === '*') {
            $protectedUrl = substr($protectedUrl, 0, strlen($protectedUrl) - 1);
            if (strpos($url, $protectedUrl) === 0) {
                $matchProtectedUrl = true;
                break;
            }
        } else {
            if ($protectedUrl ===  $url) {
                $matchProtectedUrl = true;
                break;
            }
        }
    }
    if ($matchProtectedUrl !== true) {
        return;
    }
}
```
instead of 
```
if ($settings->getProtectedUrls()) {
    if (!in_array($url, $settings->getProtectedUrls())) {
        return;
    }
}
```

Is this something you would consider useful?

### Additional info

- Plugin version: 1.2.0
- Craft version: 3.4.7.1

**Comment by engram-design** [comment]
Added Regex support in [1.2.1](https://github.com/verbb/knock-knock/releases/tag/1.2.1), so you could do `/some-channel/(.*)` to match pages.
