### ISSUE TITLE
CP Styling

### ISSUE THREAD

**Issue by jeffaglenn** [verbb/knock-knock#19]
### Description
The CP seems to have some styling issues. Nothing preventing it from working, just looks funny. It pushes the entire site down the window.

Not sure if it's related to this: #16 

### Steps to reproduce
1. Go to plugin settings

### Additional info
- Plugin version: 1.2.1
- Craft version: Craft Pro 3.4.9

<img width="1510" alt="Screen Shot 2020-03-06 at 10 50 42 AM" src="https://user-images.githubusercontent.com/34280463/76104283-b97f0b00-5f98-11ea-9c08-34a5fc076f80.png">

**Comment by engram-design** [comment]
Fixed in [1.2.2](https://github.com/verbb/knock-knock/releases/tag/1.2.2)
