### ISSUE TITLE
Protect urls vs entire site 

### ISSUE THREAD

**Issue by dgrigg** [verbb/knock-knock#20]
### Feature Request
I appreciate that you guys have run with this plugin since the Craft 2 version I created. 

I have run into a use case that Knock Knock would be perfect for with a minor tweak. The ability to protect urls specified by a regex/straight match, much like how different Craft redirect plugins work.

Let me know if that’s something you might want to add. It’s something I need in the short term so I’ll likely do it via a module but would be happy to submit a PR for it later.

**Comment by engram-design** [comment]
So worries, and for URLs - we've just added Regex support for URLs in [1.2.1](https://github.com/verbb/knock-knock/releases/tag/1.2.1) - will this work for you?

**Comment by dgrigg** [comment]
Nice. I didn’t see that in the docs. I’ll check it out.

**Comment by engram-design** [comment]
Added some clarity to the docs FYI
