### ISSUE TITLE
Issue: Interaction with Webperf plugin

### ISSUE THREAD

**Issue by richhayler** [verbb/knock-knock#23]
### Description
In some circumstances after entering the password into the knock knock password prompt I'm bring redirected to "../webperf/metrics/beacon".

Would it be possible to force redirect to the homepage or make this a config setting to set a redirect destination?

### Additional info
- Webperf version: 1.0.18
- Knock Knock version: 1.2.6
- Craft version: 3.4.15

**Comment by engram-design** [comment]
Hmmm, so it'll grab the referring URL and try and redirect back to that, so not sure why the beacon would be sending the request, and being redirected to that.

I'll investigate further, but check out [1.2.7](https://github.com/verbb/knock-knock/releases/tag/1.2.7) to make use of `forcedRedirect`.

**Comment by richhayler** [comment]
Thanks Josh, I’ve just upgraded to 1.2.7

**Comment by engram-design** [comment]
Following up in https://github.com/verbb/knock-knock/issues/31
