### ISSUE TITLE
Allow IPs after update 1.2.9.1 does not work

### ISSUE THREAD

**Issue by GMConsultant** [verbb/knock-knock#29]
### Description

I entered my ip address in the form dedicated to the list of authorized addresses after saved if I try to access another browser with which I am not logged in, I am asked for the password.
Before the last update all was ok.

### Additional info

- Plugin version: 1.2.9.1
- Craft version: 3.4.24

**Comment by engram-design** [comment]
I can't seem to replicate this, and these settings were a rename, so I don't believe there was a change in functionality. I'd just triple check you're running `1.2.9.1` and even go so far as to look in `vendor/verbb/knock-knock` and search for white/black - just to make sure.

**Comment by GMConsultant** [comment]
I confirm that if only one ip is inserted it works, but if I add another it does not work.

**Comment by engram-design** [comment]
Still can't strictly reproduce this either - but would you be able to have a go with [1.2.9.2](https://github.com/verbb/knock-knock/releases/tag/1.2.9.2)?

What OS and browser are you trying on? Are you setting these settings from the control panel, or from a config file?

**Comment by nickdenys** [comment]
It doesn't seem to be working here as well, even with only 1 IP address. It keeps showing the "Site locked" screen.
I'm setting the settings through the config file. It looks like this (password and IP address changed for security reasons):

```
<?php

return [
    '*' => [
        'enabled' => false,
        'password' => 'uZ9s:&N;]je)z%A-',
        'siteSettings' => [],
        'checkInvalidLogins' => false,
        'invalidLoginWindowDuration' => '3600',
        'maxInvalidLogins' => 10,
        'allowIps' => '194.XX.XX.XX',
        'denyIps' => '',
    ],
    'staging' => [
        'enabled' => true,
    ],
];
```

- Plugin version: 1.2.9.2
- Craft version: 3.4.27
- PHP version: 7.4.7
- OS: macOS Catalina 10.15.5
- Browser: all modern browsers, as far as I can tell

**Comment by engram-design** [comment]
I will add that logic was changed recently in 1.2.8 that changed how the IP was fetched. Previously we used:
```
$request->getUserIP();
```
The problem with this is that this uses the `X-Forwarded-For` header value, which can be spoofed to be whatever you like. This was changed to:
```
$request->getRemoteIP();
```
Which returns the IP on the other end of this connection.

I don't _think_ this should produce any different results. 

@nickdenys Just note that if you're on the page `/knock-knock/who-is-there` (the login form), and refresh the page, it won't redirect you back to where you were coming from. For example, if you try to visit the homepage, you'll be redirected to this page. Hitting refresh will just always show the page whether you're allowed or not. Can you confirm you're checking against this?

I've replicated your exact config and seems to work for me on multiple devices. I'm not sure quite what's going on, but might spin up a fresh install.

**Comment by nickdenys** [comment]
@engram-design Thanks for looking into it. I can confirm it wasn't the refresh issue you've suggested. I've also set up a fresh install to make sure it wasn't a project specific issue, but it seems to happen on fresh installs as well.

I did some further digging and it seems that the IP address it gets from the request doesn't seem to match with my actual public IP address (which I got from multiple online services). When dumping the request, it even gives me two different IP addresses when switching from WiFi to cabled internet... Granted, this isn't exactly my field of expertise but this seems fishy 🤔 Maybe an ISP or router issue? I'll keep digging when I get the chance.

**Comment by engram-design** [comment]
@nickdenys So that's interesting. The change was made due to a potential security issue where literally anyone could change their IP to an allowed one, and they'd be let in. Not very safe, but also pretty hard to guess the exact IP required in practice...

I'll have to do some more testing on my end with this, so see what I can uncover. I might just have to roll my own, rather than rely on Yii

**Comment by engram-design** [comment]
@nickdenys I'm reverting the IP check behaviour due to too many issues and edge-cases in [1.2.10](https://github.com/verbb/knock-knock/releases/tag/1.2.10)

People can opt-in to using the remote IP if security if their primary concern, but for the majority of people, this plugin serves as a simple password-protection to sites, or part of sites. I may look at more robust security handling in the future.

@GMConsultant Interested if [1.2.10](https://github.com/verbb/knock-knock/releases/tag/1.2.10) fixes this for you?

**Comment by nickdenys** [comment]
@engram-design I haven't had the chance yet for extensive testing, but the revert in 1.2.10 seems to have fixed the issue for me. Thanks for the quick update! 👏

**Comment by engram-design** [comment]
Great to hear!
