### ISSUE TITLE
“Template not found” when using multi-segment URLs

### ISSUE THREAD

**Issue by jannisborgers** [verbb/knock-knock#32]
I have a staging sites protected with Knock Knock.

- When I’m trying to access https://[domain].com/page, I get redirected to https://[domain].com/knock-knock/who-is-there as expected
- When I’m trying to access https://[domain].com/page/subpage, I get redirected to https://[domain].com/page/knock-knock/who-is-there, which leads to a “Template not found“ Craft error page.

I tried setting the custom login path to @web/knock-knock/who-is-there to make it absolute, but that lead to a redirect error in the browser, making it impossible to input the password.

I’m using Knock Knock 1.2.10 with Craft 3.4.5

**Comment by engram-design** [comment]
Fixed in [1.2.11](https://github.com/verbb/knock-knock/releases/tag/1.2.11)

**Comment by nickdenys** [comment]
@engram-design This update in 1.2.11 seems to break Knock Knock for us.
It redirects us to https://[domain].com/[baseUrl]/knock-knock/who-is-there, giving us a 404 error, saying template not found.

![image](https://user-images.githubusercontent.com/6000247/90140266-c68afc00-dd79-11ea-9781-b8cfce0affcc.png)

We have a base URL configured to `/nl`. Removing the base URL seems to clear the error again.

![image](https://user-images.githubusercontent.com/6000247/90140494-1ec1fe00-dd7a-11ea-827b-f07fc2ba3d0a.png)

I’m using Knock Knock 1.2.11 with Craft 3.5.3

**Comment by engram-design** [comment]
Should be also fixed in [1.2.12](https://github.com/verbb/knock-knock/releases/tag/1.2.12), sorry about that.

**Comment by nickdenys** [comment]
@engram-design That seemed to do the trick. Thanks for the quick fix!
On a side-note: is it possible that there's a formatting issue in the CHANGELOG.md?
Updates for Knock Knock seem different than other plugins when updating through the CP.
![image](https://user-images.githubusercontent.com/6000247/90231169-09e97700-de1b-11ea-91db-7869b6f5c70c.png)

**Comment by engram-design** [comment]
@nickdenys Ah, looks like I've just formatted something wrong...
