### ISSUE TITLE
Work with Project Config

### ISSUE THREAD

**Issue by knynkwl** [verbb/knock-knock#33]
Right now the plugin won't install via the project config.

**Comment by engram-design** [comment]
Can you expand on your issue? Are you receiving an error, and if so, what is it?

Plugin's don't get directly installed by the project config. In fact, all Knock Knock's settings are stored in the plugin settings.

**Comment by knynkwl** [comment]
Sorry, ya on my local it was installed and when pushing the project config files up to production it wasn't enabling it.

I had settings disabled on production so I have to manually enable setting and manually enable the plugin.

Maybe it is an isssue with the project config / craft? When I looked at the yml file it did say it was enabled but it wasn't :(

**Comment by engram-design** [comment]
Yeah, I've had similar issues before with other plugins, I think its a general issue with Craft and plugins. I've noticed often if I disable plugins (or enable them) its not always respected. 

What version of Craft are you on?

**Comment by knynkwl** [comment]
Hm yeah. I was using 3.5.7

**Comment by engram-design** [comment]
Closing due to age. Also believe its a Craft core issue.
