### ISSUE TITLE
Error accessing the settings

### ISSUE THREAD

**Issue by andyarc** [verbb/knock-knock#36]
**Description**
The plugin installs but accessing the settings results in an error
`Call to undefined method __TwigTemplate_ae65b81bcc86120336308bd2f36c07be584923626bfedd01eced17c1993469ff::macro_autosuggestField()`

**Steps to reproduce**
1. Install the plugin via the plugin store
2. Attempt to access the settings

**Additional info**
- Plugin version: 1.1.2
- Craft version: 3.0.41.1
- Multi-site: No

**Additional context**

Setting a knock-knock.php file shows the password entry field but upon entering the password another error `Getting unknown property: craft\config\GeneralConfig::storeUserIps`

**Comment by engram-design** [comment]
So that's a bit outdated install, but I also should've been testing down to Craft 3.0.x.

Fixed in [1.1.3](https://github.com/verbb/knock-knock/releases/tag/1.1.3)
