### ISSUE TITLE
Error on first Submittion: Request contained an invalid body param

### ISSUE THREAD

**Issue by maltemichels** [verbb/knock-knock#41]
**Description**
When I submit the Password for the first time, I get the following error: `Request contained an invalid body param`
After a Refresh it works just fine. But when I'm triggering it again (e.g. changing the needed password), I can reproduce the error. I tried it with Knock Knock's default template as well as a custom one.

**Steps to reproduce**
1. Setup Knock Knock
2. Open login path
3. Submit empty input

**Additional info**
- Plugin version: 1.2.14
- Craft version: 3.6.12.1
- Multi-site: Yes

**Comment by engram-design** [comment]
Hmm, can you outline anything about your setup that might be different to mine, as I can't replicate this. Whether it's caching, server setup or something else?

If you're able to, would you be able to inspect the page with Web Developers tools, and check out the Network tab? I'm interested in the headers that are being sent to Craft when you submit the page.

Basically, this:
![image](https://user-images.githubusercontent.com/1221575/116832671-53703100-abf9-11eb-94ac-6b7af56e05a8.png)

I would say it might be the redirect input that it's complaining about as the CSRF token being invalid would rather a 400 Bad Request error.

**Comment by maltemichels** [comment]
@engram-design That's funny – now I can't reproduce it either.
I thought maybe it's only my local setup: Laravel Mix with Valet. But now it's difficult to narrow down.

I'll keep an eye on it and if there's another occurrence, I'll share the headers.
