### ISSUE TITLE
Disable settings pane when allowAdminChanges => false

### ISSUE THREAD

**Issue by darylknight** [verbb/knock-knock#44]
**Description**
A client was asking just now (on a site that hasn't launched yet) if they could control Knock Knock via the control panel, because they need to do some penetration testing that requires access to the front end (during their business hours when I'm asleep).
I deleted the knock knock php config file and went to check on the production site if I could disable/enable knock knock for that environment through the settings window. Turns out https://tasi.bank/control/knock-knock/settings is accessible, but whenever you try to change anything you get "Administrative changes are disallowed in this environment."

I would suggest that the settings pane shouldn't be accessible at all on environments where 'allowAdminChanges' => false, or the fields are disabled and it shows a warning that they can't be changed because Project Config controls this environment.

**Comment by engram-design** [comment]
This is only really an issue if you directly go to the URL to that page though, right? The main settings page is unavailable with  `allowAdminChanges => false` so there's no way to navigate to it otherwise.

Added in [1.2.15](https://github.com/verbb/knock-knock/releases/tag/1.2.15)

**Comment by darylknight** [comment]
Yeah, that's correct I had to type the URL to get there manually. Edge case as I was trying to see if I could allow the client to do it. Not a big deal, and ended up telling them it requires a developer. Thanks!

**Comment by engram-design** [comment]
Yep, unfortunately all project-config related with plugin settings, so it's a admin-only tasks, which is a tad annoying at times.
