### ISSUE TITLE
Would not install on Craft 3.7.x

### ISSUE THREAD

**Issue by wunderbaresnet** [verbb/knock-knock#46]
I used your plugin on Craft 3.6.x - after updating to 3.7 it was gone. Control Panel said "uninstalled" and trying to install it popped up the error "plugin could not be installed".

**Comment by engram-design** [comment]
Hmmm, shouldn't have been anything to make the plugin uninstall itself. From what you're getting, it looks like the plugin files are missing altogether. Have you verified the `vendor/verbb/knock-knock` files are there, or tried `composer install verbb/knock-knock`?

**Comment by TUSAB-web** [comment]
I have the plugin installed, but it is not putting up a password request on the URL(s) specified anymore with Craft 3.7.14 and newer. I don’t have an older version available to test. Maybe related? I’ve turned the plugin on/off multiple times to see if it will start working again, but it is not protecting the specified URL(s) anymore.

**Comment by engram-design** [comment]
@TUSAB-web Are you able to share your settings? Are you having the same issue as @wunderbaresnet with the plugin showing as uninstalled?

I'll also note that if you're logged in, you won't be challenged to login, just in case that's a factor.

**Comment by TUSAB-web** [comment]
I just updated to the latest version of Craft on my local setup and now the password appears again. Perhaps there was a point release that broke something with it that they later fixed? I will deploy to my staging server and test there and then onto production. I will let you know if this fixes the problem there after I deploy.
