### ISSUE TITLE
Show Knock Knock in admin nav and allow editing

### ISSUE THREAD

**Issue by vonscriptor** [verbb/knock-knock#49]
**What are you trying to do?**
With `'allowAdminChanges' => false` there is no way to let CMS users edit plugin settings. I'd like for CMS users to be able to modify certain settings that are not controlled by the config/knock-knock.php file. They could potentially enable the plugin, change the password, update URLs and IPs.

**What's your proposed solution?**
Show Knock Knock in the admin sidebar nav with access to the plugin settings.

**Comment by vonscriptor** [comment]
It appears this cannot happen because the plugin stores its settings in the project config.

So while I'm not sure of the implications of this request it still seems as though this would be a useful feature.

**Comment by engram-design** [comment]
This can't be done sorry, as all plugin settings are stored in the project config files - we have no control over that, as it's set at the Craft level, and just how plugin settings work.

Every setting available in the interface should be available via the config file. What's an example of something you want to set, but can't?

Going to close for now, as it'd be a massive pain to have to manage these settings across multiple environments, which would put it out of project config. Unfortunately, we can't really have it both ways! (being able to have the same settings across all environments, and also change them per-environment).

**Comment by vonscriptor** [comment]
That makes sense and I expected that to be the case. I appreciate the info!

The main feature of the plugin is to lock down the entire site, but with the additional features of being able to do it based on URLs opened up some potential solutions for my clients. For example, many of them want the ability to password protect case studies and landing pages (individuals entries). It currently requires a developer to define the password and which URLs versus the client having that ability.

I can see advantages to having most settings managed in the project config. However, for this use case defining URLs and setting the password(s) is really only needed on production to make certain pages private. More so how other plugins handle redirects.

There are other plugins that offer similar features, but I just wanted to run the idea past you. I realize it goes a bit beyond the original scope of the plugin and would require a lot of rework. I'm a big fan of verbb—keep up the great work!

**Comment by engram-design** [comment]
Yep, that's fair enough! Password-protecting other pages is probably out of scope of this plugin - at the moment. As you mention, [plenty](https://plugins.craftcms.com/template-guard) [of](https://plugins.craftcms.com/serve-secret)[ other](https://plugins.craftcms.com/gatekeeper) [options](https://plugins.craftcms.com/protectedlinks) out there, and Knock Knock is primarily for locking down your site entirely.

Who knows what'll happen down the track though!
