### ISSUE TITLE
After logging in on site it doesnt redirect to the original url

### ISSUE THREAD

**Issue by amyyaling** [verbb/knock-knock#5]
### Description

I've only got Knock knock set up locally - but I have a multisite setup and I only want to apply it to one site. Lets call the primary site SiteA, and the site I want to lock SiteB.
In General settings for the plugin, I have only toggled the "Site Settings" on for SiteB, and applied a simple password. Everything else is left blank/off.
I have a craft structure section set up in SiteB and I try to access one of the entries in incognito - the login appears as normal, and the password works - however, after logging in I am redirected to SiteA homepage. 
Am I missing a step or is this the expected behavior? 

### Steps to reproduce

1. Apply plugin to one site that is not the root site
2. Login to site and notice redirect to homepage for root site

### Additional info

- Plugin version: 1.1.0
- Craft version: 3.1.5

**Comment by engram-design** [comment]
Fixed in [1.1.1](https://github.com/verbb/knock-knock/releases/tag/1.1.1)
