### ISSUE TITLE
Installing plugin gives migration error on clean craft install

### ISSUE THREAD

**Issue by Antimated** [verbb/knock-knock#52]
### Describe the bug

Knock knock is not able to install (via the CP at least) on a fresh craft 4.1.3 install.

### Steps to reproduce

1. Create a clean craft install
2. Try and install knock knock from the plugin store

### Craft CMS version

4.1.3

### Plugin version

2.0.0

### Multi-site?

No

### Additional context

Error given:
```
Migration Error: An error occurred while executing the "verbb\knockknock\migrations\Install migration: verbb\knockknock\migrations\Install::createTables(): Return value must be of type verbb\knockknock\migrations\voic, none returned
```

**Comment by engram-design** [comment]
Fixed in [2.0.1](https://github.com/verbb/knock-knock/releases/tag/2.0.1)
