### ISSUE TITLE
Plugin prevents the loading of files from /cpresources

### ISSUE THREAD

**Issue by sander-lameco** [verbb/knock-knock#56]
### Describe the bug

Currently on Craft `3.7.59` and Knock-Knock `1.2.18` when going to the login for the admin and getting redirected to the Knock-knock page there is not styling or files being loaded because they get blocked by Knock-knock.

Example can be found here: https://xximo-staging.lamecoserver.com/nl-en/knock-knock/who-is-there

I already have the following data in the `Unprotected URLs` with the first one being our CPAdminSlug :
```
/craft-cms/(.*)/
cpresources/(.*)
```

### Steps to reproduce

Very basic installation of the plugin with just the plugin enabled and a password (Set via .env file) and the `Unprotected URLs` are set via the `project.yml` because somehow an array in the `config/knock-knock.php` gives an error.

### Craft CMS version

3.7.59

### Plugin version

1.2.18

### Multi-site?

Yes

### Additional context

This is happening on the staging environment but am unable to reproduce this on my local machine.
We are planning to update this site to Craft 4 in the future.

**Comment by engram-design** [comment]
I'm not seeing that at all on my end, but it also does somewhat make sense that it _might_ be happening because all site requests are being checked. We can add a exception to this for `cpresources` although not quite sure why styles are loading for me.

**Comment by sander-lameco** [comment]
Thats weird indeed, this is a screenshot the way I see it, also you can see the errors in the console. The unexpected token `<` is from the `<!DOCTYPE html>` in the Knock-knock screen.

![Screenshot 2022-11-01 at 15 54 01](https://user-images.githubusercontent.com/25500086/199263772-042269de-c665-44c8-b809-bf841e6426ca.png)

**Comment by engram-design** [comment]
Hmmm, Craft takes care of resource requests [way before](https://github.com/craftcms/cms/blob/2eac9249964ccc553bf841c79b9ee44d58f16b61/src/web/Application.php#L158) we hit Knock Knock.

I notice you've got your install setup using subfolders? Are you also specifically setting `resourceBaseUrl` in your general config?

I'm even spitting out some debug info [here](https://github.com/verbb/knock-knock/blob/a914146d1fb36dd8badfc01e421c60e923b9443f/src/KnockKnock.php#L74) and there's no requests to `/cpresources` at all. And yes, I've cleared the caches just to be sure.

If you're up for debugging, you can add:

```php
file_put_contents('request.txt', print_r($request->getFullPath() . PHP_EOL, true), FILE_APPEND);
```

Which will create a `request.txt` file and append every request that comes in to that file, to see what's being passed through Knock Knock.

**Comment by sander-lameco** [comment]
First of all thanks for taking the time to help us out.

I'm not sure what you mean with setup using subfolders, we use the basic craft installation in the root and have a really basic general config:

``` php
<?php

use craft\helpers\App;

$isDev = App::env('ENVIRONMENT') === 'dev';
$isProd = App::env('ENVIRONMENT') === 'production';

return [
    'defaultWeekStartDay' => 1,
    'omitScriptNameInUrls' => true,
    'cpTrigger' => App::env('CP_TRIGGER') ?: 'admin',
    'securityKey' => App::env('SECURITY_KEY'),
    'devMode' => $isDev,
    'allowAdminChanges' => $isDev,
    'disallowRobots' => !$isProd,
    'upscaleImages' => false,
    'aliases' => [
        '@web' => craft\helpers\App::env('PRIMARY_SITE_URL'),
        '@gtmId' => craft\helpers\App::env('GOOGLETAGMANAGER_ID'),
        '@googleMapsKey' => craft\helpers\App::env('GOOGLE_MAPS_KEY'),
    ],
];
```

Do I put the debug line anywhere in the KnockKnock.php?

**Comment by engram-design** [comment]
Your config all looks good to me, and as for where to add that code, add it [here](https://github.com/verbb/knock-knock/blob/a914146d1fb36dd8badfc01e421c60e923b9443f/src/KnockKnock.php#L74)

**Comment by sander-lameco** [comment]
Sorry for the late response. Currently the staging environment is actively being used by the client. I hope to add the debugging log next tuesday.

**Comment by sander-lameco** [comment]
I'm closing this issue because we stopped using the plugin in favor of .htpasswd. Sorry for not being able to tackle the issue and thank you for trying to help and understanding.
