### ISSUE TITLE
Should /admin but accessible even when KnockKnock is enabled?

### ISSUE THREAD

**Issue by engram-design** [verbb/knock-knock#58]
### Discussed in https://github.com/verbb/knock-knock/discussions/57

<div type='discussions-op-text'>

<sup>Originally posted by **RyanRoberts** December 10, 2022</sup>
I've used KK for ages without issue but for some reason I thought if you have a user account you can bypass KK and just go straight to the CP admin and login without entering the KK password. But at the moment KK is redirecting me to the locked page whenever I try to access the CP.

I've added /admin/(.*) to the unprotected URLS and I can access it but it gives me an undefined error.

The reason I'm asking this is because I have KK acting as a holding page *without* the password field, I was hoping to then login and access the site as normal. </div>

**Comment by engram-design** [comment]
@RyanRoberts I believe this was an error in [2.0.4](https://github.com/verbb/knock-knock/releases/tag/2.0.4) where we enforce CP challenges, as some users want to lock down the CP login screen behind another layer with Knock Knock.

Fixed in [2.0.6](https://github.com/verbb/knock-knock/releases/tag/2.0.6)

**Comment by RyanRoberts** [comment]
Thanks! At least I know I'm not going crazy now 😆
