### ISSUE TITLE
Whitelisted IPs not coming through

### ISSUE THREAD

**Issue by EternalBlack** [verbb/knock-knock#6]
### Description

I have some whitelisted IPs but unfortunately they still see the login/password template when requesting the site.

I assume checking if the requesting IP is inside the whitelist [here](https://github.com/verbb/knock-knock/blob/87a15e0f9794d21d12e755e1cc7d2205cb9c9b1f/src/KnockKnock.php#L79) would work.

```php
$ipAddress = Craft::$app->getRequest()->getUserIP();
```
and
```php
!in_array($ipAddress, $settings->getWhitelistIps())
```
probably does the trick.

### Additional info

- Plugin version: 1.1.0
- Craft version: 3.1.30 Pro

**Comment by engram-design** [comment]
Right, so whitelisting is just for whitelisting against lockouts - as in they'll never get locked out with the number of failed tries to login, but makes complete sense to whitelist to not show the prompt as you mention.

**Comment by engram-design** [comment]
This is now possible in [1.1.1](https://github.com/verbb/knock-knock/releases/tag/1.1.1)
