### ISSUE TITLE
Multiple Unprotected URLs Not work in Control Panel UI

### ISSUE THREAD

**Issue by adrianjean** [verbb/knock-knock#60]
### Describe the bug

**Issue:**
- Adding multiple Unprotected URLs (one on each line) in the CraftCMS Control Panel settings for Knock Knock (not the `/config/knock-knock.php`) causes the plugin to not allow any Unprotected URLs
- Adding only one Unprotected URL, behaves as intend

**Expected Behaviour:**
- Adding multiple Unprotected URLs (one on each line) disables Knock Knock protection on each URL specified

**Notes:**
- Adding multiple Unprotected URLs using the `/config/knock-knock.php` settings file, works as intended.

### Steps to reproduce

1. 
2. 

### Craft CMS version

4.3.6.1

### Plugin version

2.0.6

### Multi-site?

No

**Comment by alexroper** [comment]
To piggyback off of @adrianjean, I'm also running into this bug with the "Protected URLs" field in the control panel. One protected URL works fine. Two protected URLs in the field disables the protected URLs feature (neither work).

Craft CMS 4.3.6.1
Knock Knock 2.0.6
Multi-site? No

**Comment by engram-design** [comment]
Fixed in [2.0.7](https://github.com/verbb/knock-knock/releases/tag/2.0.7)
