### ISSUE TITLE
Incorrect array for getUnprotectedUrls()

### ISSUE THREAD

**Issue by arnout-poppr** [verbb/knock-knock#62]
### Describe the bug

Was trying to add an unprotected api endpoint on my platform when encountering that the config option `unprotectedUrls` had no effect whatsoever. When looking into it, this was because the URL's are being added to the wrong array: `$protectedUrls` instead of `$unprotectedUrls`.

![Screenshot 2023-03-01 131351](https://user-images.githubusercontent.com/94955382/222136907-75a7abe1-916c-4ca0-9f6b-8d28798c83c7.png)

Thanks for all your work on this plugin.

### Steps to reproduce

1.  Add `unprotectedUrls` array to `knock-knock.php`
2.  The URL's in the `unprotectedUrls` array are still protected by Knock Knock

### Craft CMS version

4.3.10

### Plugin version

2.0.7

### Multi-site?

No

**Comment by engram-design** [comment]
Do'h, good pickup there, looks like an error from 2.0.7. Fixed in [2.0.8](https://github.com/verbb/knock-knock/releases/tag/2.0.8)
