### ISSUE TITLE
Multi-site - how should the config file be structured?

### ISSUE THREAD

**Issue by andreimoment** [verbb/knock-knock#69]
### Question

Adding a second site to a craftcms installation, I tried using knock-knock to gate the second site's content until approved.

However, knock-knock caused for both sited to be gated.

If site_2 was set to enabled, site_1 would also get gated on production. The settings in the CP would show site_1 as not gated, but on the production it would be gated.

Should I use a different config file structure?

This was my config file:

~~~php

<?php

return [
    '*' => [

        'siteSettings' => [
            'site_1' => [
                'enabled' => false,
            ],
            'site_2' => [
                'enabled' => true,
                'password' => 'the-pasword',
            ],
        ],

        'checkInvalidLogins' => false,
        'invalidLoginWindowDuration' => '3600',
        'maxInvalidLogins' => 10,
        'allowIps' => '',
        'denyIps' => '',
        'useRemoteIp' => false,

        'protectedUrls' => '',
        'unprotectedUrls' => '',
    ],
    'dev' => [
        'enabled' => true,
    ],
    'production' => [
        'enabled' => true,
    ]
];
~~~

**Comment by engram-design** [comment]
I believe this issue here is setting `enabled` on `dev` and `production` which overrides any site-specific settings. Removing that (or replacing it with `siteSettings` in your different environments) should do the trick.

The [docs](https://verbb.io/craft-plugins/knock-knock/docs/get-started/configuration#multi-site-configuration) state this:

> If you keep the top level `enabled`, `password`, etc settings, they'll override your settings for each site.

**Comment by andreimoment** [comment]
Thank you, I will try this.
