### ISSUE TITLE
Multi-site and Multi-enviroment configuration

### ISSUE THREAD

**Issue by samuel-clara** [verbb/knock-knock#70]
### What are you trying to do?

I have a project where it would be convenient to have the plugin enabled baset on site handle and the current environment. So it would be perfect if we could configure the plugin like below:

### What's your proposed solution?

```
return [
    '*' => [
        'siteSettings' => [
            'siteHandle' => [
                'enabled' => false,
                'dev' => [
                    'enabled' => false
                ],
                'staging' => [
                    'enabled' => true
                ]
            ],
            'anotherSiteHandle' => [
                'dev' => [
                    'enabled' => false
                ],
                'staging' => [
                    'enabled' => true
                ]
            ],
        ]
    ],
];
```

**Comment by engram-design** [comment]
That's exactly what you can do according to the [docs](https://verbb.io/craft-plugins/knock-knock/docs/get-started/configuration#multi-site-configuration) - is that not working? I will note that you need to invert your environment handles:

```php
return [
    'dev' => [
        'siteSettings' => [
            'siteHandle' => [
                'enabled' => false,
            ],
            'anotherSiteHandle' => [
                'enabled' => false,
            ],
        ]
    ],
    'staging' => [
        'siteSettings' => [
            'siteHandle' => [
                'enabled' => true,
            ],
            'anotherSiteHandle' => [
                'enabled' => true,
            ],
        ]
    ],
];
```

**Comment by samuel-clara** [comment]
Oh thank you my fault! I inverted the environment handles following your example and it works properly.

**Comment by engram-design** [comment]
Yep, to be fair I should mention a link to the [Craft docs](https://craftcms.com/docs/4.x/config/#multi-environment-configs) about this.
