### ISSUE TITLE
Craft 5 upgrade issue

### ISSUE THREAD

**Issue by splendidrob** [verbb/knock-knock#73]
### Describe the bug

Running composer update as per the Craft 5 upgrade I'm getting an error for Knock Knock:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - verbb/knock-knock 3.0.0-beta.1 requires verbb/base ^3.0.0-beta.1 -> found verbb/base[3.0.0-beta.1] but it does not match your minimum-stability.
    - Root composer.json requires verbb/knock-knock 3.0.0-beta.1 -> satisfiable by verbb/knock-knock[3.0.0-beta.1].
 ```

Seems slightly odd to me as looks like I do have the minimum required version...

### Steps to reproduce

1. Follow upgrade instructions for Craft 5 and add new versions for all plugins in composer.json
2. run composer update

### Craft CMS version

2.0.48.1

### Plugin version

2.0.11

### Multi-site?

no

**Comment by splendidrob** [comment]
Added "verbb/base": "3.0.0-beta.1", to my composer.json which seems to have sorted this...

**Comment by engram-design** [comment]
Strange, that should be all means work, and you shouldn't need to require `verbb/base` specifically. 

You might like to try: `composer require "verbb/knock-knock:^3.0.0-beta.1" -w`

**Comment by splendidrob** [comment]
Couldnt quite get that to work - running as part of the Craft 5 upgrade process it wouldn't allow me to install using the above require command due to requiring Craft 5, but I cant install Craft 5 without upgrading knock knock...so I just added the base again...

**Comment by engram-design** [comment]
Thanks for letting me know, I'll continue to look into what's going on here. I've yet to encounter this one in the wild.

One other thing to check was your `minimum-stability` setting in `composer.json` if you have that set.
