### ISSUE TITLE
php craft setup/welcome fails when knock knock plugin is installed in project config. 

### ISSUE THREAD

**Issue by Numkil** [verbb/knock-knock#75]
### Describe the bug

Hi

Because we have a "base install" from which we regularly start new projects, we run the php craft setup/welcome command from within a project that already has a project-config but no database yet.

We have noticed that, starting from craft 5.2.0, doing this fails if the knock-knock plugin is already installed. We then get the following error.

![Screenshot 2024-07-01 at 12 37 47](https://github.com/user-attachments/assets/212ead28-35ab-4d96-89fe-c13b555d92e3)

We have a config/knock-knock.php file in which we specify the plugin is disabled by default but the code still goes to check the primary site first. Because the primary site does not yet exist at this point I presume the craft/welcome command fails. 

Is this something that could be fixed on your end or should this be something that craft handles.

Thank you for at least reading this :) 

### Steps to reproduce

1. Using ddev as an example
2. Go to any preconfigured craft ^5.2.0 project you have lying around with knock knock installed
3. start with ddev but do not import the database for it.
4. instead run ddev craft setup/welcome

### Craft CMS version

5.2.4.1

### Plugin version

3.0.0

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/knock-knock:"dev-craft-5 as 3.0.0"`.

**Comment by Numkil** [comment]
Awesome thank you!
