### ISSUE TITLE
FR: Could it be possible to exclude certain IP's from knock knock

### ISSUE THREAD

**Issue by ghost** [verbb/knock-knock#8]
When a site is on staging it would be nice to exclude our own IP from Knock Knock so we don't have to fill in the password every time the cookie expires. This would be handy when we are entering content for longer periods of time or, when using a multisite, switching between websites.

**Comment by engram-design** [comment]
This is now possible in [1.1.1](https://github.com/verbb/knock-knock/releases/tag/1.1.1)
